### ISSUE TITLE
cutechess with large concurrency at short TCs leads to time losses.

### ISSUE THREAD

**Issue by vondele** [cutechess/cutechess#630]
## Output of `cutechess-cli --version` / `cutechess --version`
$ ./cutechess-cli --version
cutechess-cli 1.1.0
Using Qt version 5.10.1

## How did you run Cute Chess exactly?

./cutechess-cli -repeat -rounds 10000 -games 2 -tournament round-robin -srand 1942127704 -resign movecount=3 score=400 -draw movenumber=34 movecount=8 score=20 -concurrency 128 -openings file=noob_3moves.epd format=epd order=random plies=16 -engine name=master cmd=stockfish.master  -engine name=patch cmd=stockfish.patch -each proto=uci tc=10.0+0.1 -ratinginterval 1 -pgnout foo.pgn

## Expected behavior

no time losses observed during match.

##Actual behavior

observed a number of time losses. Can be seen locally as well as on fishtest when a worker with a large number of cores joins.

## Steps to reproduce the behavior

run the above command or similar on a machine with >= 64 threads. 
A workaround is to run multiple cutechess processes e.g. 8  with concurrency 16, instead of 1 with concurrency 128. 

**Screenshots**
N/A

**Comment by vondele** [comment]
I'll move some data here from the fishtest issue where we started discussing:

 On a machine with 128cores/256threads I look at timeout stats as a function of cutechess concurrency (threads in the table) and TC.

```
   threads         TC  timed-out /      total
       240   4.0+0.04        940 /       1000 ( 94%)
       128   4.0+0.04        886 /       1000 ( 89%)
       120   4.0+0.04        863 /       1000 ( 87%)
       100   4.0+0.04        559 /       1000 ( 56%)
        80   4.0+0.04         10 /       1000 (  1%)
        64   4.0+0.04          0 /       1000 (  0%)
       240   10.0+0.1        777 /        960 ( 81%)
       128   10.0+0.1        108 /        512 ( 22%)
       120   10.0+0.1         57 /        480 ( 12%)
       100   10.0+0.1         10 /        400 (  3%)
        80   10.0+0.1          0 /        320 (  0%)
        64   10.0+0.1          0 /        256 (  0%)
       240   60.0+0.6          2 /        960 (  1%)
       128   60.0+0.6          0 /        512 (  0%)
       120   60.0+0.6          0 /        480 (  0%)
       100   60.0+0.6          0 /        400 (  0%)
        80   60.0+0.6          0 /        320 (  0%)
        64   60.0+0.6          0 /        256 (  0%)
```

it definitely shows the problem is mostly showing up with relatively short TC games and larger concurrency. The precise values will be hardware/OS dependent, I assume, but the trend is clear.

**Comment by vondele** [comment]
If I remove output of the pgn, and just looking at the short TC games, it appears to improve already a bit:
```
   threads         TC  timed-out /      total
       240   4.0+0.04        863 /        960 ( 90%)
       128   4.0+0.04        281 /        512 ( 55%)
       120   4.0+0.04        164 /        480 ( 35%)
       100   4.0+0.04         43 /        400 ( 11%)
        80   4.0+0.04          1 /        320 (  1%)
        64   4.0+0.04          0 /        256 (  0%)
```

**Comment by vondele** [comment]
@alwey suggested that this could be related to parsing PVs. I couldn't test an earlier cutechess version, but I realized that I could test the same engine (stockfish) but with the output modified:
* single pv move only, for each depth (shortpv)
* single pv move only, but only for last depth (once)
I upgraded the SF branch (from pre-nnue to nnue), and output changed a bit, so I provide the master reference as well as the 'nopv' and 'once' result:
```
master:
   threads         TC  timed-out /      total
       240   4.0+0.04        785 /        960 ( 82%)
       128   4.0+0.04         63 /        512 ( 13%)
       120   4.0+0.04         42 /        480 (  9%)
       100   4.0+0.04          1 /        400 (  1%)
        80   4.0+0.04          0 /        320 (  0%)
        64   4.0+0.04          0 /        134 (  0%)
shortpv:
   threads         TC  timed-out /      total
       240   4.0+0.04        731 /        960 ( 77%)
       128   4.0+0.04          6 /        512 (  2%)
       120   4.0+0.04          0 /        480 (  0%)
       100   4.0+0.04          0 /        400 (  0%)
        80   4.0+0.04          0 /        320 (  0%)
        64   4.0+0.04          0 /        256 (  0%)
once:
   threads         TC  timed-out /      total
       240   4.0+0.04         82 /        960 (  9%)
       128   4.0+0.04         19 /        512 (  4%)
       120   4.0+0.04          0 /        480 (  0%)
       100   4.0+0.04          0 /        400 (  0%)
        80   4.0+0.04          0 /        320 (  0%)
        64   4.0+0.04          0 /        256 (  0%)
```
so indeed it looks like cutechess can't keep up with all output that it is being sent.

**Comment by alwey** [comment]
@vondele: Thank you for the series of tests. The SAN conversion eats away much of the available processing power of the main thread.

cutechess-cli has not been used much with very high concurrencies at short time controls yet, but rather with long (external testing) or very long time controls (e.g. TCEC). Now since high-core systems take part in fishtest the problem becomes both obvious and relevant.

**Comment by gaintpd** [comment]
Could you post your cpu configuration?

**Comment by vondele** [comment]
This particular test was on a dual-socket EPYC 7742, CentOS Linux 7. 

However, machines running on fishtest are other kinds as well. E.g. look at the bottom of this page 
https://tests.stockfishchess.org/tests/view/5f74aec5f18675b1ce2f73df 
grandphish2 is having a 88 cores windows machine. 
Or here:
https://tests.stockfishchess.org/tests/view/5f8eb4be2c92c7fe3a8c602a
a user pemo-64cores-11, 64 cores, unknown linux.

Note that the problems go away lauching multiple cutechess processes with each correspondingly reduced concurrency. So, hardware/OS can deal with it, IMO.

**Comment by lucasart** [comment]
@vondele: Can you try to reproduce with c-chess-cli instead ? It's a cutechess-cli clone I wrote. Would be interested to see what happens in these extreme testing conditions.

Download and compile (simple C program, no dependencies):
```
git clone https://github.com/lucasart/c-chess-cli.git
cd c-chess-cli
./make.py
```
Run your test (adapted syntax):
```
./c-chess-cli \
-each tc=4.0+0.04 option.Hash=4 -engine name=master cmd=./master -engine name=patch cmd=./patch \
-openings noob_3moves.epd -random -repeat -resign 3,400 -draw 8,20 \
-games 20000 -concurrency 128 -pgn foo.pgn
```
You can add `-log` to the above, which will produce full I/O logging (including stderr). It will generate 128 files, one per thread.

**Comment by vondele** [comment]
@lucasart yes I've done that a couple of days ago. I have 10% time losses with normal IO and about 5% with limited IO. (TC 4+0.04, concurrency 250).

**Comment by lucasart** [comment]
That's interesting because c-chess-cli does not do the 'PGN Queue from master thread' thing from cutechess (whose intended purpose is to guarantee that PGNs are ordered sequentially). It does I/O in the least contented way that is possible, from the workers, which put the PGN of the game in a string, then write that string to the file, with a single `fputs()` call. Of course, `fputs()` takes a file lock, but this is the minimum contention you must have if you want a single PGN (rather than one PGN per thread).

**Comment by vondele** [comment]
I think I ran c-chess-cli without the pgn option:
```
./c-chess-cli -each tc=4+0.04 option.Hash=8 option.Threads=1     -engine cmd=./stockfish.master -engine cmd=./stockfish.master     -games 2000 -concurrency 250 -openings noob_3moves.epd -random -repeat     -resign 3,700 -draw 8,10 >& out
```

**Comment by vondele** [comment]
BTW, just to make sure, when I run 25 c-chess-cli process in parallel, each of concurrency 10, there is no single loss in time.
```
for i in `seq 1 25`
do
./c-chess-cli -each tc=4+0.04 option.Hash=8 option.Threads=1     -engine cmd=./stockfish.master -engine cmd=./stockfish.master     -games 80 -concurrency 10 -openings noob_3moves.epd -random -repeat     -resign 3,700 -draw 8,10 >& out_many_$i &
done
wait

```

**Comment by Equalizer-0** [comment]
@vondele @lucasart - After upgrade from the 3700x 8core/16thread CPU to the 5950x 16core/32thread I agreed with these strange results.

5950x - tc=6.0+0.1
Score of eng1 vs eng2: 265 - 713 - 3022  [**0.444**] 4000 - 41:23 min. -concurrency 32 - cpu 100%
Score of eng1 vs eng2: 213 - 144 - 3643  [**0.509**] 4000 - 76:19 min. -concurrency 16 - cpu 50%

Does it also happen to you that if you use the CPU at 100% using all the threads it reports a result opposites to using only half the thread 50%?

**Comment by Equalizer-0** [comment]
@lucasart Congratulations for your program, unfortunately I can't compile it.
I installed MinGW, Python, but it doesn't compile, maybe some library is missing?

Microsoft Windows [Versione 10.0.19045.4170]
(c) Microsoft Corporation. Tutti i diritti sono riservati.

d:\source C++\c-chess-cli>make.py
Traceback (most recent call last):
  File "D:\source C++\c-chess-cli\make.py", line 14, in <module>
    version = subprocess.run(['git', 'show','-s','--format=%ci'], stdout=subprocess.PIPE).stdout.split()[0].decode('utf-8')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

**Comment by xoto10** [comment]
> ... Of course, `fputs()` takes a file lock, but this is the minimum contention you must have if you want a single PGN (rather than one PGN per thread).

Would it be possible for the workers to send file output to a single process (either the master thread or a new output thread)  via pipes or similar method and have that process write the output?
